#!/bin/sh

launchctl unload /var/jb/Library/LaunchDaemons/com.dinhnguyenx.ccshortcutlauncher.resolver.plist >/dev/null 2>&1 || true
launchctl load /var/jb/Library/LaunchDaemons/com.dinhnguyenx.ccshortcutlauncher.resolver.plist >/dev/null 2>&1 || true
exit 0
